name             'web_application'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures web_application'
long_description 'Installs/Configures web_application'
version          '0.3.0'

depends 'windows', '~> 1.36.6'
depends 'iis', '~> 4.1.0'
