---
driver:
  name: vagrant

provisioner:
  name: chef_zero_scheduled_task

platforms:
  - name: windows-2012r2
    transport:
      username: Administrator

suites:
  - name: default
    run_list:
      - recipe[awesome_customers::default]
    attributes:
      sql_server:
        sysadmins: ['Administrators']
